[package]
name = "configuration"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition.workspace = true
license.workspace = true

[dependencies]
ansi_term = { package = "nu-ansi-term", version = "0.50.3", default-features = false }
zellij-tile = { path = "../../zellij-tile" }
chrono = "0.4.0"
